image: maven:latest
cache:
  key: "$CI_PIPELINE_ID"
  paths:
    - ./target
variables:
  DURATION: 20
  MAVEN_CLI_OPTS: ""    #-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  INSTANCE: "devopsdemo01.service-now.com"
  TOOLID: "990300211bdad410ef803223cc4bcb0e"
stages:
  - build
  - uat
  - test
  - prod
build:
  stage: build

  script:
    - echo "\nBuilding"
    - mvn $MAVEN_CLI_OPTS compile verify
    - echo "Registering artifact"
    - |
      curl --fail --output "/dev/null" --silent --show-error --write-out "HTTP response: ${http_code}\n\n" \
      --data "{\"artifacts\" : [ { \"name\": \"globex-web.war\", \"repositoryName\": \"demorepo\", \"version\": \"3.0.${CI_PIPELINE_ID}\", \"semanticVersion\": \"3.0.${CI_PIPELINE_ID}\"} ], \"projectName\": \"${CI_PROJECT_TITLE}#${CI_JOB_NAME}\", \"taskExecutionNumber\": \"${CI_JOB_ID}\" }" \
      --header "Content-Type: application/json" --request POST \
      "https://devops.integration.user:devops@$INSTANCE/api/sn_devops/v1/devops/artifact/registration?orchestrationToolId=$TOOLID"
    - echo "Status- $?"
uat:
  stage: uat
 
  script:
    - echo "Deploy to UAT"
    
test:
  stage: test
 
  script:
    - echo "Testing"
    - mvn $MAVEN_CLI_OPTS test
    - echo "Register package"
    - |
      curl -i \
        --data "{\"artifacts\": [ { \"name\": \"globex-web.war\", \"repositoryName\": \"demorepo\", \"version\": \"3.0.${CI_PIPELINE_ID}\" } ], \"projectName\": \"${CI_PROJECT_TITLE}#${CI_JOB_NAME}\", \"taskExecutionNumber\": \"${CI_JOB_ID}\", \"name\": \"CorpSite\" }" \
        --header "Content-Type: application/json" \
        --request POST \
        "https://devops.integration.user:devops@$INSTANCE/api/sn_devops/v1/devops/package/registration?orchestrationToolId=$TOOLID"
    - echo "Status- $?"
prod:
  stage: prod
  before_script:
   - apt-get update -y && apt-get install openssh-client -y 
   - eval $(ssh-agent -s)
   - echo "$DEMO_KEY" | tr -d '\r' | ssh-add -
   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh
  script:
    - echo "Deploy in Production"
    - scp -o StrictHostKeyChecking=no globex-web.war ec2-user@3.23.165.149:/opt/tomcat/webapps
    
  when: manual
  allow_failure: false