image: maven:latest

cache:
  key: "$CI_PIPELINE_ID"
  paths:
    - ./target

variables:
  DURATION: 20
  MAVEN_CLI_OPTS: ""    #-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  INSTANCE: "devopsdemo01.service-now.com"
  TOOLID: "990300211bdad410ef803223cc4bcb0e"
  REPONAME: "demorepo"
  ARTNAME: "globex-web.war"
  ARTVERSION: "3.0.${CI_PIPELINE_ID}"
  COMPANY: "globex"

stages:
  - build
  - uat
  - test
  - prod

build:
  stage: build
  tags:
    - ec2
  script:
    - echo "\nBuilding"
    - mvn $MAVEN_CLI_OPTS compile verify
    - echo "Registering artifact"
    - |
      curl --fail --output "/dev/null" --silent --show-error --write-out "HTTP response: ${http_code}\n\n" \
      --data "{\"artifacts\" : [ { \"name\": \"$ARTNAME\", \"repositoryName\": \"$REPONAME\", \"version\": \"$ARTVERSION\", \"semanticVersion\": \"$ARTVERSION\"} ], \"projectName\": \"${CI_PROJECT_TITLE}#${CI_JOB_NAME}\", \"taskExecutionNumber\": \"${CI_JOB_ID}\" }" \
      --header "Content-Type: application/json" --request POST \
      "https://devops.integration.user:devops@$INSTANCE/api/sn_devops/v1/devops/artifact/registration?orchestrationToolId=$TOOLID"
    - echo "Status- $?"

uat:
  stage: uat
  tags:
    - ec2
  script:
    - echo "Deploy to UAT"
    

test:
  stage: test
  tags:
    - ec2
  script:
    - echo "Testing"
    - mvn $MAVEN_CLI_OPTS test
    - echo "Register package"
    - |
      curl -i \
        --data "{\"artifacts\": [ { \"name\": \"$ARTNAME\", \"repositoryName\": \"$REPONAME\", \"version\": \"$ARTVERSION\" } ], \"projectName\": \"${CI_PROJECT_TITLE}#${CI_JOB_NAME}\", \"taskExecutionNumber\": \"${CI_JOB_ID}\", \"name\": \"${COMPANY}_Globex\" }" \
        --header "Content-Type: application/json" \
        --request POST \
        "https://devops.integration.user:devops@$INSTANCE/api/sn_devops/v1/devops/package/registration?orchestrationToolId=$TOOLID"
    - echo "Status- $?"
prod:
  stage: prod
  tags:
    - ec2
  script:
    - echo "Deploy in Production"
    - cp -f target/globex-web.war /opt/tomcat/webapps
    - curl "https://devopsdemo01.service-now.com/api/snc/discoip?ip=3.23.165.149" --request GET --header "Accept:application/json" --user "srvcacct":"devops" 1>/dev/null 2>/dev/null
  when: manual
  allow_failure: false
